### ISSUE TITLE
SurveyQuestion - better error message for many-to-many mapping 

### ISSUE THREAD

**Issue by mitzimorris** [lauken13/mrpkit#111] opened 2021-07-05 16:01 UTC
The SurveyQuestion allows many-to-one, one-to-many, and one-to-one mappings.
the error message for a many-to-many mapping is confusing:
"Error: Package can only handle many to one mappings"

this should say something like "Error, many-to-many mappings not allowed" and should identify the problematic labels.

e.g.
```
mapping = list(
+     "A" = "B1",
+     "B" = "B1",
+     "B" = "B2")
```

**Comment by lauken13** [comment] 2021-07-05 21:50
Hey Mitzi,

Could you submit a reproducible example for this one please?

**Comment by mitzimorris** [comment] 2021-07-10 00:13
```
marstat_mapping = list(
    "Never married" = "Never married/single",
    "Domestic / civil partnership" = "Married, spouse present",
    "Married" = "Married, spouse present",
    "Married" = "Married, spouse absent",
    "Separated" = "Separated",
    "Divorced" = "Divorced",
    "Widowed" = "Widowed"
)
q_marstat <- SurveyQuestion$new(name = "marstat",
    col_names = c("marstat", "MARST"),
    values_map= marstat_mapping)
```

**Comment by lauken13** [comment] 2021-08-03 07:17
I can't replicate, but closing because I think this is covered in example 6 of the mapping tests, and I think this was created before pull request #103, which solved a number of mapping bugs and warnings.

**Closed by lauken13** 2021-08-03 07:17 UTC
Labels: bug
